#!/bin/sh

for filename in ../geojson/*.geojson; do
	result=$(curl -X POST --data @$filename $data http://geojsonlint.com/validate 2>/dev/null)
	if [ "$result" = "{\"status\": \"ok\"}" ]; then
		echo "Valid GeoJSON!"
	else
		echo "Invalid GeoJSON"
		exit 1
	fi
done
exit 0