#!/bin/sh

errors=0
for filename in ./geojson/*.geojson; do
	result=$(curl -X POST --data @$filename $data http://geojsonlint.com/validate 2>/dev/null)
	if [ "$result" = "{\"status\": \"ok\"}" ]; then
		echo $filename "passed GeoJSON validation."
	else
		echo $filename "FAILED GeoJSON validation."
		errors=1
	fi
done
exit $errors