#!/bin/sh

errors=0
cd $TRAVIS_BUILD_DIR/geojson
for filename in *.geojson; do
	result=$(curl -X POST --data @$filename $data http://geojsonlint.com/validate 2>/dev/null)
	if [ "$result" = "{\"status\": \"ok\"}" ]; then
		echo $filename "passed GeoJSON validation."
	else
		echo $filename "FAILED GeoJSON validation."
		errors=1
	fi
done
exit $errors